-- Insert 6 featured trips with correct column names
INSERT INTO public.packaged_trips (
  id, slug, title, destination, description, price_per_person, currency, duration_days, duration_nights,
  cover_image_url, activity_level, included, not_included, highlights,
  min_participants, max_participants, status, is_featured,
  recommended_arrival_airport, recommended_departure_airport,
  faqs, creator_type
) VALUES 
(
  gen_random_uuid(),
  'amalfi-coast',
  'Amalfi Coast Long Weekend',
  'Amalfi Coast, Italy',
  'Experience the stunning beauty of Italy''s most iconic coastline. Wander through pastel-colored villages perched on dramatic cliffs, savor fresh seafood and limoncello, and cruise along crystal-clear waters. This curated 4-night escape blends romance, culinary discovery, and coastal adventure.',
  2499,
  'USD',
  5,
  4,
  'https://images.unsplash.com/photo-1633321702518-7fecdafb94d5?w=1200',
  'Easy',
  '["4 nights boutique hotel accommodation", "Daily breakfast", "Private boat tour along the coast", "Cooking class with local chef", "Wine tasting experience", "Airport transfers", "Local guide for walking tours"]'::jsonb,
  '["International flights", "Travel insurance", "Personal expenses", "Gratuities"]'::jsonb,
  '["Sunset boat cruise to hidden coves", "Handmade pasta cooking class", "Private limoncello tasting", "Scenic Path of the Gods hike"]'::jsonb,
  2,
  12,
  'published',
  true,
  'Naples International Airport (NAP)',
  'Naples International Airport (NAP)',
  '[{"question": "What is the best time to visit?", "answer": "April to June and September to October offer the best weather and fewer crowds.", "category": "Travel"}, {"question": "Is this trip suitable for solo travelers?", "answer": "Absolutely! Many of our guests travel solo and find it a wonderful way to meet like-minded travelers.", "category": "Booking"}]'::jsonb,
  'platform'
),
(
  gen_random_uuid(),
  'cape-town',
  'Cape Town & Winelands',
  'Cape Town, South Africa',
  'Discover the vibrant culture, stunning landscapes, and world-class wines of South Africa''s crown jewel. From Table Mountain to the rolling vineyards of Stellenbosch, this 6-night journey combines adventure, gastronomy, and natural beauty.',
  3299,
  'USD',
  7,
  6,
  'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200',
  'Moderate',
  '["6 nights luxury accommodation", "Daily breakfast", "Table Mountain cable car tickets", "Full-day winelands tour with tastings", "Cape Peninsula guided tour", "Private airport transfers"]'::jsonb,
  '["International flights", "Travel insurance", "Lunches and dinners not specified", "Personal expenses"]'::jsonb,
  '["Sunrise hike up Lion''s Head", "Private wine blending experience", "Penguin colony visit at Boulders Beach", "Cape of Good Hope scenic drive"]'::jsonb,
  2,
  10,
  'published',
  true,
  'Cape Town International Airport (CPT)',
  'Cape Town International Airport (CPT)',
  '[{"question": "Do I need a visa?", "answer": "US, UK, and EU citizens do not need a visa for stays under 90 days.", "category": "Travel"}, {"question": "Is it safe?", "answer": "Cape Town is very tourist-friendly. We provide safety tips and our guides know all the best areas.", "category": "Safety"}]'::jsonb,
  'platform'
),
(
  gen_random_uuid(),
  'kyoto',
  'Kyoto Cultural Immersion',
  'Kyoto, Japan',
  'Step into ancient Japan with this intimate 5-night cultural immersion. Experience traditional tea ceremonies, wander through bamboo groves, and stay in an authentic ryokan.',
  3799,
  'USD',
  6,
  5,
  'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200',
  'Easy',
  '["5 nights accommodation (3 nights boutique hotel, 2 nights traditional ryokan)", "Daily breakfast, 2 traditional dinners", "Private tea ceremony experience", "Geisha district evening tour", "Bamboo forest guided walk"]'::jsonb,
  '["International flights", "Travel insurance", "Most lunches", "Personal shopping"]'::jsonb,
  '["Private tea ceremony with a master", "Authentic ryokan stay with kaiseki dinner", "Early morning Arashiyama bamboo walk", "Evening stroll through Gion district"]'::jsonb,
  1,
  8,
  'published',
  true,
  'Kansai International Airport (KIX)',
  'Kansai International Airport (KIX)',
  '[{"question": "Do I need to speak Japanese?", "answer": "Not at all! Our guides are fluent in English and most tourist areas have English signage.", "category": "Language"}]'::jsonb,
  'platform'
),
(
  gen_random_uuid(),
  'santorini',
  'Santorini Sunset Escape',
  'Santorini, Greece',
  'Lose yourself in the iconic blue domes and breathtaking sunsets of Santorini. This 4-night escape combines the best of Greek island life - from wine tastings in volcanic vineyards to sailing the caldera at golden hour.',
  2899,
  'USD',
  5,
  4,
  'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200',
  'Easy',
  '["4 nights cave hotel with caldera views", "Daily breakfast", "Private catamaran sunset cruise", "Wine tour with volcanic vineyard tastings", "Ancient Akrotiri archaeological tour"]'::jsonb,
  '["International flights", "Travel insurance", "Lunches and most dinners", "Water activities"]'::jsonb,
  '["Sunset catamaran cruise with champagne", "Wine tasting at cliff-side wineries", "Blue dome photo tour in Oia", "Fresh seafood dinner by the caldera"]'::jsonb,
  2,
  10,
  'published',
  true,
  'Santorini Airport (JTR)',
  'Santorini Airport (JTR)',
  '[{"question": "When is the best time to visit?", "answer": "May-June and September-October have perfect weather and smaller crowds than peak summer.", "category": "Travel"}]'::jsonb,
  'platform'
),
(
  gen_random_uuid(),
  'bali',
  'Bali Wellness Retreat',
  'Bali, Indonesia',
  'Reset your mind, body, and spirit in the spiritual heart of Bali. This 7-night wellness journey takes you from jungle yoga retreats to sacred water temples, with daily spa treatments and plant-based cuisine.',
  2199,
  'USD',
  8,
  7,
  'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200',
  'Easy',
  '["7 nights eco-luxury resort accommodation", "All meals (plant-based options available)", "Daily yoga and meditation sessions", "3 spa treatments", "Sacred water temple blessing ceremony"]'::jsonb,
  '["International flights", "Travel insurance", "Personal expenses", "Optional activities"]'::jsonb,
  '["Daily sunrise yoga overlooking rice terraces", "Traditional Balinese healing ceremony", "Organic farm-to-table dining", "Waterfall meditation experience"]'::jsonb,
  1,
  12,
  'published',
  true,
  'Ngurah Rai International Airport (DPS)',
  'Ngurah Rai International Airport (DPS)',
  '[{"question": "Do I need yoga experience?", "answer": "No! Our classes cater to all levels, from complete beginners to advanced practitioners.", "category": "Activity"}]'::jsonb,
  'platform'
),
(
  gen_random_uuid(),
  'patagonia',
  'Patagonia Adventure',
  'Patagonia, Argentina & Chile',
  'Embark on the adventure of a lifetime through the wild, untamed beauty of Patagonia. Trek past towering glaciers, navigate pristine fjords, and witness landscapes that will take your breath away.',
  4499,
  'USD',
  9,
  8,
  'https://images.unsplash.com/photo-1531761535209-180857e963b9?w=1200',
  'Challenging',
  '["8 nights mixed accommodation (lodges and eco-camps)", "All meals during expedition", "Expert bilingual mountain guide", "Torres del Paine National Park fees", "Perito Moreno Glacier tour"]'::jsonb,
  '["International flights", "Travel insurance (mandatory)", "Personal trekking gear", "Alcoholic beverages", "Gratuities"]'::jsonb,
  '["Sunrise at Torres del Paine peaks", "Ice trekking on Perito Moreno Glacier", "Wildlife spotting (guanacos, condors)", "Stargazing in zero light pollution"]'::jsonb,
  4,
  10,
  'published',
  true,
  'El Calafate Airport (FTE)',
  'Punta Arenas Airport (PUQ)',
  '[{"question": "How fit do I need to be?", "answer": "Moderate-to-good fitness required. We include hikes of 4-8 hours on some days with elevation changes.", "category": "Fitness"}]'::jsonb,
  'platform'
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  destination = EXCLUDED.destination,
  description = EXCLUDED.description,
  price_per_person = EXCLUDED.price_per_person,
  duration_days = EXCLUDED.duration_days,
  duration_nights = EXCLUDED.duration_nights,
  cover_image_url = EXCLUDED.cover_image_url,
  activity_level = EXCLUDED.activity_level,
  included = EXCLUDED.included,
  not_included = EXCLUDED.not_included,
  highlights = EXCLUDED.highlights,
  faqs = EXCLUDED.faqs,
  status = EXCLUDED.status,
  is_featured = EXCLUDED.is_featured;