// This file is automatically generated. If you regenerate it, make sure
// the placeholder fallbacks are NOT reintroduced.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Read Supabase config from environment - NO FALLBACKS
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate configuration - fail fast if misconfigured
const isInvalidConfig =
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  SUPABASE_URL.includes("placeholder.supabase.co") ||
  SUPABASE_URL.includes("your-project.supabase.co") ||
  SUPABASE_PUBLISHABLE_KEY.includes("your-supabase-anon-key") ||
  SUPABASE_PUBLISHABLE_KEY === "public-anon-key";

if (isInvalidConfig) {
  const errorMessage =
    "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables.";

  console.error(errorMessage, {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    url: SUPABASE_URL || "(not set)",
  });

  // ALWAYS throw - don't silently use bad config in any environment
  throw new Error(errorMessage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
