// This file is automatically generated. You can safely customize the
// configuration behavior, but keep the client shape the same.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const FALLBACK_SUPABASE_URL = "https://placeholder.supabase.co";
const FALLBACK_SUPABASE_KEY = "public-anon-key";

// Use real env vars if present, otherwise fall back to placeholders.
// This keeps the UI working even if Supabase is not fully configured.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY;

const isPlaceholderConfig =
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  SUPABASE_URL.includes("your-project.supabase.co") ||
  SUPABASE_URL.includes("placeholder.supabase.co") ||
  SUPABASE_PUBLISHABLE_KEY.includes("your-supabase-anon-key") ||
  SUPABASE_PUBLISHABLE_KEY === "public-anon-key";

// In production (including Lovable preview), DO NOT crash the app.
// Just log an error so we know Supabase is not really configured.
if (import.meta.env.PROD && isPlaceholderConfig) {
  console.error(
    "[Supabase] Using placeholder configuration in production. " +
      "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for real auth."
  );
}

// In dev, log a more gentle warning.
if (import.meta.env.DEV && isPlaceholderConfig) {
  console.warn(
    "[Supabase] Using placeholder configuration. " +
      "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for full functionality."
  );
}

// Import the supabase client like this:
//   import { supabase } from "@/integrations/supabase/client"
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
